### ISSUE TITLE
This error occured when I plug my HDMI in my laptop.

### ISSUE THREAD

**Issue by vault-me** [praisenter/praisenter#40]
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.praisenter.data.workspace.DisplayConfiguration.getId()" because "configuration" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniRunNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniRunStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenRunAsync(Unknown Source)
	at org.praisenter.ui.LoadingPane.loadDisplayManager(LoadingPane.java:295)
	at org.praisenter.ui.LoadingPane.lambda$start$40(LoadingPane.java:402)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at org.praisenter.async.AsyncHelper.apply(AsyncHelper.java:137)
	at org.praisenter.async.AsyncHelper.lambda$onSpecificThreadAndWait$3(AsyncHelper.java:119)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "org.praisenter.data.workspace.DisplayConfiguration.getId()" because "configuration" is null
	at org.praisenter.ui.display.DisplayManager.getScreenDisplayState(DisplayManager.java:258)
	at org.praisenter.ui.display.DisplayManager.onScreensChanged(DisplayManager.java:152)
	at org.praisenter.ui.display.DisplayManager.initialize(DisplayManager.java:55)
	at org.praisenter.ui.LoadingPane.lambda$loadDisplayManager$22(LoadingPane.java:292)
	at org.praisenter.async.AsyncHelper.run(AsyncHelper.java:171)
	at org.praisenter.async.AsyncHelper.lambda$onSpecificThreadAndWait$8(AsyncHelper.java:162)
	... 14 more

**Comment by wnbittle** [comment]
Thank you for reporting this.  To help troubleshoot, does the application work if the HDMI display is already plugged in before starting the application?

**Comment by wnbittle** [comment]
This should be fixed in 3.1.5 that will be released on the Windows/Snap store in the next few days
